### ISSUE TITLE
Python 2.6: No module named _fileio

### ISSUE THREAD

**Issue by Symbian9** [deadsnakes/issues#127] opened 2020-07-14 01:05 UTC
### description

I use complete install of Python 2.6 for Bionic, but seems like `_fileio` module missed in distribution:

- https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa/+sourcepub/9018171/+listing-archive-extra

### os information

Bionic

#### lsb_release -a

```
# paste the output of `lsb_release -a` here
```

#### uname -a

```
# paste the output of `uname -a` here
```

**Comment by asottile** [comment] 2020-07-14 01:19
do you have a stacktrace or other output?

I cannot reproduce your findings:

```console
root@addc85a2f6c6:/# python2.6
Python 2.6.9 (default, Apr 29 2018, 12:56:59) 
[GCC 7.3.0] on linux4
Type "help", "copyright", "credits" or "license" for more information.
>>> import io
>>> import _fileio
>>> 
```

**Comment by Symbian9** [comment] 2020-07-14 01:43
I'm trying to use official *Blender* `2.49b` binary under Bionic with deadsnakes' Pthon2.6 installed:

- https://download.blender.org/release/Blender2.49b/blender-2.49b-linux-glibc236-py26-x86_64.tar.bz2

Here is error output in interactive console inside Blender on trying to import `io`:

![pic.1](https://i.imgur.com/Fqzd9Bc.png)

**Comment by asottile** [comment] 2020-07-14 03:02
is there a reason you're trying to use something compiled in 2009?  there's newer versions of blender available

`_fileio` isn't provided as a `lib-dynload` module, in the debian builds `_fileio` is included as a builtin module (meaning it is part of the executable itself)

**Comment by asottile** [comment] 2020-07-14 03:13
just to make double sure, can you confirm what version of the deadsnakes package you're using? you failed to fill out the issue template and I haven't seen anything that indicates this is our problem

**Comment by Symbian9** [comment] 2020-07-14 03:39
> is there a reason you're trying to use something compiled in 2009? there's newer versions of blender available

In my case I need exactly *Blender* `2.49b`.

> just to make double sure, can you confirm what version of the deadsnakes package you're using?

I already linked it header post, but here it is: `python2.6 (2.6.9-3.2+bionic2)`

- https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa/+sourcepub/9018171/+listing-archive-extra

> `_fileio` isn't provided as a `lib-dynload` module, in the debian builds `_fileio` is included as a builtin module (meaning it is part of the executable itself)

Any workaround possible without recompiling everything?

**Comment by asottile** [comment] 2020-07-14 04:00
it sounds like blender is calling out to `python` or `python2` which is python2.7 and that's trying to execute the `io` module (the internals of `io` moved between the two versions) -- can you try putting them earlier on the `PATH`? something like:

```bash
mkdir bin
ln -s python2.6 bin/python2
ln -s python2.6 bin/python
export PATH=$PWD/bin:$PATH
blender ...
```

**Comment by Symbian9** [comment] 2020-07-14 04:28
>  can you try putting them earlier on the `PATH`?

As I use `blender-softwaregl` Shell-script to launch Blender 2.49b, may you point me out where to put needed variable into this script?

```Shell
#!/bin/sh

BF_DIST_BIN=`dirname "$0"`
BF_PROGRAM="blender" # BF_PROGRAM=`basename "$0"`-bin
exitcode=0

# PATH=${BF_DIST_BIN}/bin:${PATH}

# PYTHONHOME=${BF_DIST_BIN}/lib:${PYTHONHOME}

# PYTHONPATH=${BF_DIST_BIN}/lib:${PYTHONPATH}

LD_LIBRARY_PATH=${BF_DIST_BIN}/lib:${LD_LIBRARY_PATH}

if [ -n "$LD_LIBRARYN32_PATH" ]; then
    LD_LIBRARYN32_PATH=${BF_DIST_BIN}/lib:${LD_LIBRARYN32_PATH}
fi
if [ -n "$LD_LIBRARYN64_PATH" ]; then
    LD_LIBRARYN64_PATH=${BF_DIST_BIN}/lib:${LD_LIBRARYN64_PATH}
fi
if [ -n "$LD_LIBRARY_PATH_64" ]; then
    LD_LIBRARY_PATH_64=${BF_DIST_BIN}/lib:${LD_LIBRARY_PATH_64}
fi

# Workaround for half-transparent windows when compiz is enabled
XLIB_SKIP_ARGB_VISUALS=1

# PYTHONPATH PYTHONHOME PATH 
export LD_LIBRARY_PATH LD_LIBRARYN32_PATH LD_LIBRARYN64_PATH LD_LIBRARY_PATH_64 LD_PRELOAD XLIB_SKIP_ARGB_VISUALS

# strace ./blender-softwaregl &> strace.log
"$BF_DIST_BIN/$BF_PROGRAM" ${1+"$@"}
exitcode=$?
exit $exitcode
```

**Comment by asottile** [comment] 2020-07-14 05:30
it wouldn't just be variables, did you try what I suggested above?

either way, the package is correct and contains the `_fileio` module and unfortunately I can't help you debug further for free so I'm going to close this -- sorry

**Closed by asottile** 2020-07-14 05:30 UTC

**Comment by Symbian9** [comment] 2020-07-14 18:30
> either way, the package is correct and contains the `_fileio` module and unfortunately I can't help you debug furthe

Well, I just found `_fileio.so` as separate file module for Python `2.6.6` and placed it into `lib-dynload` — and now *Blender* `2.49b`could use it without errors!

- https://cibilbao.com/bilbao360/bilbao360/env/lib/python2.6/lib-dynload/_fileio.so
