### ISSUE TITLE
python3.8-distutils conflicts with bionic system

### ISSUE THREAD

**Issue by stub42** [deadsnakes/issues#122] opened 2020-06-15 07:56 UTC
### description

The python3.8-distutils package appears to conflict with bionic's python3-distutils package. Also the python3.8-lib2to3 dependency of python3.8-distutils conflicts with bionic's python3-lib2to3

```
root@bio:~# sudo apt install python3.8-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3.8-dev is already the newest version (3.8.3-1+bionic1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@bio:~# sudo apt install python3.8-distutils
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  python3.8-lib2to3
The following NEW packages will be installed:
  python3.8-distutils python3.8-lib2to3
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/314 kB of archives.
After this operation, 1235 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
(Reading database ... 64515 files and directories currently installed.)
Preparing to unpack .../python3.8-lib2to3_3.8.0-1+bionic2_all.deb ...
Unpacking python3.8-lib2to3 (3.8.0-1+bionic2) ...
dpkg: error processing archive /var/cache/apt/archives/python3.8-lib2to3_3.8.0-1+bionic2_all.deb (--unpack):
 trying to overwrite '/usr/lib/python3.8/lib2to3/Grammar.txt', which is also in package python3-lib2to3 3.6.9-1~18.04
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Preparing to unpack .../python3.8-distutils_3.8.0-1+bionic2_all.deb ...
Unpacking python3.8-distutils (3.8.0-1+bionic2) ...
dpkg: error processing archive /var/cache/apt/archives/python3.8-distutils_3.8.0-1+bionic2_all.deb (--unpack):
 trying to overwrite '/usr/lib/python3.8/distutils/README', which is also in package python3-distutils 3.6.9-1~18.04
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/python3.8-lib2to3_3.8.0-1+bionic2_all.deb
 /var/cache/apt/archives/python3.8-distutils_3.8.0-1+bionic2_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

#### lsb_release -a

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

#### uname -a

```
Linux bio 5.4.0-37-generic #41-Ubuntu SMP Wed Jun 3 18:57:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by asottile** [comment] 2020-06-15 15:36
dupe of #98 #99 #100

we no longer build this package and I haven't found a way to delete it from the ppa (it's not listed anywhere on the pages)

**Closed by asottile** 2020-06-15 15:36 UTC

**Comment by stub42** [comment] 2020-06-16 03:31
https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa/+delete-packages is the deletion UI (linked from the top right of https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa/+packages under 'copy packages' and the logout button. Maybe this page lets you do the surgery you need. It looks like I can delete all debs created from the python3.8-3.8.0-1+bionic2 source package which I think would solve this particular issue?

**Comment by asottile** [comment] 2020-06-16 04:53
OH! nice yeah I think that'll do it -- just deleted those -- thanks!
